
import React from 'react';
import { 
  Truck, 
  Stethoscope, 
  Users, 
  BookOpen, 
  Sprout, 
  Wallet, 
  Home, 
  MessageSquare, 
  UserCircle,
  CloudSun,
  Bike,
  Car,
  Navigation,
  Circle,
  Wrench,
  Zap,
  Hammer,
  HardHat,
  Settings,
  Trash2,
  HandHelping,
  Wheat,
  Siren,
  Flame,
  ShieldAlert,
  PhoneCall,
  Hospital,
  Pill,
  Activity,
  HeartPulse,
  PlusSquare
} from 'lucide-react';

export const COLORS = {
  primary: '#0F7A5D',
  accent: '#F6A623',
  background: '#FAFBFC',
  danger: '#E53E3E',
};

export const TRANSPORT_TYPES = [
  { id: 'all', name: 'All', icon: <Truck size={18} /> },
  { id: 'bike', name: 'Bike', icon: <Bike size={18} /> },
  { id: 'auto', name: 'Auto', icon: <Navigation size={18} /> },
  { id: 'car', name: 'Car', icon: <Car size={18} /> },
  { id: 'tractor', name: 'Tractor', icon: <Truck size={18} /> },
  { id: 'pickup', name: 'Pickup', icon: <Truck size={18} /> },
  { id: 'tempo', name: 'Tempo', icon: <Truck size={18} /> },
  { id: 'shared', name: 'Shared', icon: <Users size={18} /> },
];

export const WORKER_TYPES = [
  { id: 'all', name: 'All', icon: <Users size={18} /> },
  { id: 'farm', name: 'Farm Labor', icon: <Wheat size={18} /> },
  { id: 'electrician', name: 'Electrician', icon: <Zap size={18} /> },
  { id: 'plumber', name: 'Plumber', icon: <Wrench size={18} /> },
  { id: 'carpenter', name: 'Carpenter', icon: <Hammer size={18} /> },
  { id: 'mason', name: 'Mason', icon: <HardHat size={18} /> },
  { id: 'mechanic', name: 'Mechanic', icon: <Settings size={18} /> },
  { id: 'cleaner', name: 'Cleaner', icon: <Trash2 size={18} /> },
  { id: 'general', name: 'General', icon: <HandHelping size={18} /> },
];

export const MEDICAL_TYPES = [
  { id: 'all', name: 'All', icon: <Activity size={18} /> },
  { id: 'hospital', name: 'Hospital', icon: <Hospital size={18} /> },
  { id: 'clinic', name: 'Clinic', icon: <PlusSquare size={18} /> },
  { id: 'pharmacy', name: 'Pharmacy', icon: <Pill size={18} /> },
  { id: 'doctor', name: 'Doctor', icon: <Stethoscope size={18} /> },
  { id: 'health_worker', name: 'Health Worker', icon: <HeartPulse size={18} /> },
];

export const SERVICES = [
  { id: 'emergency', name: 'Emergency', nameHi: 'आपातकालीन', icon: <Siren />, category: 'Safety' },
  { id: 'transport', name: 'Transport', nameHi: 'परिवहन', icon: <Truck />, category: 'Utility' },
  { id: 'medical', name: 'Medical', nameHi: 'चिकित्सा', icon: <Stethoscope />, category: 'Health' },
  { id: 'workers', name: 'Workers', nameHi: 'श्रमिक', icon: <Users />, category: 'Labour' },
  { id: 'education', name: 'Education', nameHi: 'शिक्षा', icon: <BookOpen />, category: 'Info' },
  { id: 'mandi', name: 'Mandi', nameHi: 'मंडी', icon: <Sprout />, category: 'Market' },
  { id: 'wallet', name: 'Wallet', nameHi: 'बटुआ', icon: <Wallet />, category: 'Finance' },
];

export const TRANSLATIONS = {
  en: {
    welcome: 'Welcome to Village Connect',
    selectLanguage: 'Select Language',
    login: 'Login',
    enterPhone: 'Enter Phone Number',
    sendOtp: 'Send OTP',
    verifyOtp: 'Verify OTP',
    sos: 'SOS',
    home: 'Home',
    mandi: 'Mandi',
    wallet: 'Wallet',
    chats: 'Chats',
    profile: 'Profile',
    mandiPrices: 'Mandi Prices',
    sellProduce: 'Sell Produce',
    buyProduce: 'Buy Produce',
    bookNow: 'Book Now',
    lowBalance: 'Low Balance',
    currentBalance: 'Current Balance',
    history: 'History',
    rolePrompt: 'Select your role',
    iAmFarmer: 'I am a Farmer / User',
    iAmProvider: 'I am a Service Provider',
    kycNote: 'Service providers need to verify Aadhaar.',
    payVerification: 'Pay ₹1 for Verification',
    tokenAmount: 'Verification Transaction: ₹5',
    offlineNote: 'Showing last updated prices (Offline Mode)',
    reportIssue: 'Report Local Issue',
    rewardEarned: 'Reward Earned!',
    weatherTitle: 'Weather Forecast',
    agricultureTip: 'Farmer Advice',
    humidity: 'Humidity',
    wind: 'Wind',
    viewDetails: 'View Details',
    pickupLocation: 'Pickup Location',
    dropLocation: 'Drop Location',
    estimatedFare: 'Estimated Fare',
    paymentMethod: 'Payment Method',
    cash: 'Cash',
    walletPay: 'Wallet',
    confirmTrip: 'Confirm Trip',
    jobDescription: 'Job Description',
    estimatedDuration: 'Estimated Duration',
    totalEstimated: 'Total Estimated Cost',
    confirmHiring: 'Confirm Hiring',
    emergencyServices: 'Emergency Services',
    ambulance: 'Ambulance',
    police: 'Police',
    fire: 'Fire Brigade',
    helpOnWay: 'Help is on the way!',
    locating: 'Locating you...',
    alertingResponders: 'Alerting nearest responders...',
    callNow: 'Call Directly',
    cancelAlert: 'Cancel Emergency Alert',
  },
  hi: {
    welcome: 'विलेज कनेक्ट में आपका स्वागत है',
    selectLanguage: 'भाषा चुनें',
    login: 'लॉगिन',
    enterPhone: 'फ़ोन नंबर दर्ज करें',
    sendOtp: 'ओटीपी भेजें',
    verifyOtp: 'ओटीपी सत्यापित करें',
    sos: 'आपातकालीन (SOS)',
    home: 'होम',
    mandi: 'मंडी',
    wallet: 'बटुआ',
    chats: 'चैट',
    profile: 'प्रोफ़ाइल',
    mandiPrices: 'मंडी भाव',
    sellProduce: 'उपज बेचें',
    buyProduce: 'उपज खरीदें',
    bookNow: 'अभी बुक करें',
    lowBalance: 'कम बैलेंस',
    currentBalance: 'वर्तमान बैलेंस',
    history: 'इतिहास',
    rolePrompt: 'अपनी भूमिका चुनें',
    iAmFarmer: 'मैं एक किसान / उपयोगकर्ता हूँ',
    iAmProvider: 'मैं एक सेवा प्रदाता हूँ',
    kycNote: 'सेवा प्रदाताओं को आधार सत्यापित करना होगा।',
    payVerification: 'सत्यापन के लिए ₹1 का भुगतान करें',
    tokenAmount: 'सत्यापन लेनदेन: ₹5',
    offlineNote: 'अंतिम अपडेट भाव (ऑफलाइन मोड)',
    reportIssue: 'स्थानीय समस्या की रिपोर्ट करें',
    rewardEarned: 'इनाम मिला!',
    weatherTitle: 'मौसम का पूर्वानुमान',
    agricultureTip: 'किसान सलाह',
    humidity: 'नमी',
    wind: 'हवा',
    viewDetails: 'विवरण देखें',
    pickupLocation: 'पिकअप स्थान',
    dropLocation: 'ड्रॉप स्थान',
    estimatedFare: 'अनुमानित किराया',
    paymentMethod: 'भुगतान का तरीका',
    cash: 'नकद',
    walletPay: 'बटुआ',
    confirmTrip: 'ट्रिप की पुष्टि करें',
    jobDescription: 'कार्य का विवरण',
    estimatedDuration: 'अनुमानित समय',
    totalEstimated: 'कुल अनुमानित लागत',
    confirmHiring: 'नियुक्ति की पुष्टि करें',
    emergencyServices: 'आपातकालीन सेवाएं',
    ambulance: 'एम्बुलेंस',
    police: 'पुलिस',
    fire: 'दमकल विभाग',
    helpOnWay: 'मदद रास्ते में है!',
    locating: 'आपकी स्थिति खोज रहे हैं...',
    alertingResponders: 'सहायकों को सूचित कर रहे हैं...',
    callNow: 'सीधे कॉल करें',
    cancelAlert: 'अलर्ट रद्द करें',
  }
};
